# # services:
# #   postgres:
# #     image: postgres:13
# #     restart: always
# #     environment:
# #       POSTGRES_DB: nakama
# #       POSTGRES_USER: nakama
# #       POSTGRES_PASSWORD: examplepassword
# #     volumes:
# #       - pgdata:/var/lib/postgresql/data
# #     ports:
# #       - "5432:5432"

# #   nakama:
# #     build: ./backend
# #     depends_on:
# #       - postgres
# #     environment:
# #       - "socket.server_key=defaultkey"
# #       - "session.encryption_key=exampleencryptionkey1234567890"
# #       - "database.address=postgres:5432"
# #     ports:
# #       - "7350:7350"
# #       - "7351:7351"

# # volumes:
# #   pgdata:

# version: '3'
# services:
#   postgres:
#     command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
#     environment:
#       - POSTGRES_DB=nakama
#       - POSTGRES_PASSWORD=localdb
#     expose:
#       - "8080"
#       - "5432"
#     image: postgres:12.2-alpine
#     ports:
#       - "5432:5432"
#       - "8080:8080"
#     volumes:
#       - data:/var/lib/postgresql/data

#   nakama:
#     build: .
#     depends_on:
#       - postgres
#     entrypoint:
#       - "/bin/sh"
#       - "-ecx"
#       - >
#         /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
#         exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama
#     expose:
#       - "7349"
#       - "7350"
#       - "7351"
#     healthcheck:
#       test: ["CMD", "/nakama/nakama", "healthcheck"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     links:
#       - "postgres:db"
#     ports:
#       - "7349:7349"
#       - "7350:7350"
#       - "7351:7351"
#     restart: unless-stopped

# volumes:
#   data:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-nakama}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-nakama}",
        ]
      interval: 2s
      timeout: 2s
      retries: 30

  nakama:
    build: ./
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - "database.address=${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}"
      - "database.name=${POSTGRES_DB:-nakama}"
      - "database.user=${POSTGRES_USER:-postgres}"
      - "database.password=${POSTGRES_PASSWORD:-postgres}"
      - "socket.server_key=${NAKAMA_SERVER_KEY:-defaultkey}"
      - "logger.level=debug"
    ports:
      - "7350:7350"
      - "7351:7351"
    volumes:
      - ./config:/nakama/data:ro
      - ./modules:/nakama/data/modules:ro

volumes:
  pgdata:
